package com.hibdb;

// Generated Jul 23, 2013 3:54:21 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Alarms generated by hbm2java
 */
public class Alarm implements java.io.Serializable {

	private Integer id;
	private String descr;
	private int owner;
	private Date instant;
	private boolean priv;

	public Alarm() {
		this.owner = 0;
		this.instant = new Date(0);
		this.priv = false;
	}

	public Alarm(int owner, Date instant, boolean priv) {
		this.owner = owner;
		this.instant = instant;
		this.priv = priv;
	}

	public Alarm(String descr, int owner, Date instant, boolean priv) {
		this.descr = descr;
		this.owner = owner;
		this.instant = instant;
		this.priv = priv;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public int getOwner() {
		return this.owner;
	}

	public void setOwner(int owner) {
		this.owner = owner;
	}

	public Date getInstant() {
		return this.instant;
	}

	public void setInstant(Date instant) {
		this.instant = instant;
	}

	public boolean isPriv() {
		return this.priv;
	}

	public void setPriv(boolean isPrivate) {
		this.priv = isPrivate;
	}

}
