package com.hibdb;

// Generated Jul 23, 2013 3:54:21 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Alarms generated by hbm2java
 */
public class Alarm implements java.io.Serializable {

	private Integer id;
	private String descr;
	private int owner;
	private Date instant;
	private boolean isPrivate;

	public Alarm() {
	}

	public Alarm(int owner, Date instant, boolean isPrivate) {
		this.owner = owner;
		this.instant = instant;
		this.isPrivate = isPrivate;
	}

	public Alarm(String descr, int owner, Date instant, boolean isPrivate) {
		this.descr = descr;
		this.owner = owner;
		this.instant = instant;
		this.isPrivate = isPrivate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public int getOwner() {
		return this.owner;
	}

	public void setOwner(int owner) {
		this.owner = owner;
	}

	public Date getInstant() {
		return this.instant;
	}

	public void setInstant(Date instant) {
		this.instant = instant;
	}

	public boolean isIsPrivate() {
		return this.isPrivate;
	}

	public void setIsPrivate(boolean isPrivate) {
		this.isPrivate = isPrivate;
	}

}
